-- ============================================================
-- OLIST E-COMMERCE SQL QUERY BANK
-- Author  : Patrick Lie (TP066914)
-- Dataset : Olist Brazilian E-Commerce (Kaggle)
-- Purpose : Portfolio – Data Analyst SQL Skill Demonstration
-- Levels  : Beginner → Intermediate → Advanced
-- ============================================================

-- ============================================================
-- TABLE REFERENCE (Olist Schema)
-- ============================================================
-- olist_orders_dataset            → orders (o)
-- olist_order_items_dataset       → order_items (oi)
-- olist_order_payments_dataset    → payments (p)
-- olist_order_reviews_dataset     → reviews (r)
-- olist_customers_dataset         → customers (c)
-- olist_sellers_dataset           → sellers (s)
-- olist_products_dataset          → products (pr)
-- olist_product_category_name_translation → category (cat)
-- ============================================================


-- ============================================================
-- LEVEL 1: BEGINNER
-- Core: SELECT, WHERE, GROUP BY, ORDER BY, LIMIT, HAVING
-- ============================================================

-- ----------------------------------------------------------
-- Q1. How many orders does Olist have in total?
-- Business use: Baseline KPI for business size overview
-- ----------------------------------------------------------
SELECT COUNT(order_id) AS total_orders
FROM olist_orders_dataset;


-- ----------------------------------------------------------
-- Q2. What are the possible order statuses and how many per status?
-- Business use: Order fulfillment health check
-- ----------------------------------------------------------
SELECT
    order_status,
    COUNT(order_id) AS total_orders
FROM olist_orders_dataset
GROUP BY order_status
ORDER BY total_orders DESC;


-- ----------------------------------------------------------
-- Q3. Which are the top 10 product categories by number of items sold?
-- Business use: Identify bestselling categories for inventory planning
-- ----------------------------------------------------------
SELECT
    cat.product_category_name_english AS category,
    COUNT(oi.order_item_id)           AS items_sold
FROM olist_order_items_dataset oi
JOIN olist_products_dataset pr
    ON oi.product_id = pr.product_id
JOIN olist_product_category_name_translation cat
    ON pr.product_category_name = cat.product_category_name
GROUP BY cat.product_category_name_english
ORDER BY items_sold DESC
LIMIT 10;


-- ----------------------------------------------------------
-- Q4. What is the total revenue generated by Olist?
-- Business use: Top-line revenue reporting
-- ----------------------------------------------------------
SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue_brl
FROM olist_order_payments_dataset;


-- ----------------------------------------------------------
-- Q5. What is the average order review score?
-- Business use: Customer satisfaction benchmark
-- ----------------------------------------------------------
SELECT
    ROUND(AVG(review_score), 2) AS avg_review_score
FROM olist_order_reviews_dataset;


-- ----------------------------------------------------------
-- Q6. Which states have the most customers?
-- Business use: Geographic market concentration analysis
-- ----------------------------------------------------------
SELECT
    customer_state,
    COUNT(customer_id) AS total_customers
FROM olist_customers_dataset
GROUP BY customer_state
ORDER BY total_customers DESC
LIMIT 10;


-- ----------------------------------------------------------
-- Q7. How many orders were placed each year?
-- Business use: Year-over-year growth tracking
-- ----------------------------------------------------------
SELECT
    YEAR(order_purchase_timestamp)  AS year,
    COUNT(order_id)                 AS total_orders
FROM olist_orders_dataset
GROUP BY YEAR(order_purchase_timestamp)
ORDER BY year;


-- ----------------------------------------------------------
-- Q8. What payment types do customers prefer?
-- Business use: Payment channel optimization
-- ----------------------------------------------------------
SELECT
    payment_type,
    COUNT(order_id)                                         AS usage_count,
    ROUND(SUM(payment_value), 2)                            AS total_value_brl,
    ROUND(AVG(payment_value), 2)                            AS avg_value_brl
FROM olist_order_payments_dataset
GROUP BY payment_type
ORDER BY usage_count DESC;


-- ============================================================
-- LEVEL 2: INTERMEDIATE
-- Core: JOINs, Subqueries, CASE WHEN, date functions, HAVING
-- ============================================================

-- ----------------------------------------------------------
-- Q9. What is the monthly revenue trend? (2017–2018)
-- Business use: Seasonality and growth trend analysis
-- ----------------------------------------------------------
SELECT
    DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS month,
    ROUND(SUM(p.payment_value), 2)                    AS monthly_revenue_brl,
    COUNT(DISTINCT o.order_id)                        AS total_orders
FROM olist_orders_dataset o
JOIN olist_order_payments_dataset p
    ON o.order_id = p.order_id
WHERE o.order_status = 'delivered'
GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
ORDER BY month;


-- ----------------------------------------------------------
-- Q10. What is the average delivery time per state?
-- Business use: Logistics performance benchmarking by region
-- ----------------------------------------------------------
SELECT
    c.customer_state,
    COUNT(o.order_id)                                              AS delivered_orders,
    ROUND(AVG(DATEDIFF(
        o.order_delivered_customer_date,
        o.order_purchase_timestamp
    )), 1)                                                         AS avg_delivery_days
FROM olist_orders_dataset o
JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id
WHERE o.order_status = 'delivered'
  AND o.order_delivered_customer_date IS NOT NULL
GROUP BY c.customer_state
ORDER BY avg_delivery_days ASC;


-- ----------------------------------------------------------
-- Q11. Which sellers generate the most revenue?
-- Business use: Top seller identification for partnership programs
-- ----------------------------------------------------------
SELECT
    oi.seller_id,
    s.seller_city,
    s.seller_state,
    COUNT(DISTINCT oi.order_id)         AS total_orders,
    ROUND(SUM(oi.price), 2)             AS total_revenue_brl,
    ROUND(AVG(oi.price), 2)             AS avg_order_value_brl
FROM olist_order_items_dataset oi
JOIN olist_sellers_dataset s
    ON oi.seller_id = s.seller_id
GROUP BY oi.seller_id, s.seller_city, s.seller_state
ORDER BY total_revenue_brl DESC
LIMIT 20;


-- ----------------------------------------------------------
-- Q12. What is the relationship between delivery time and review score?
-- Business use: Prove fast delivery = better reviews (SLA justification)
-- ----------------------------------------------------------
SELECT
    CASE
        WHEN DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp) <= 7  THEN '0–7 days'
        WHEN DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp) <= 14 THEN '8–14 days'
        WHEN DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp) <= 21 THEN '15–21 days'
        WHEN DATEDIFF(o.order_delivered_customer_date, o.order_purchase_timestamp) <= 30 THEN '22–30 days'
        ELSE '30+ days'
    END                             AS delivery_bucket,
    COUNT(o.order_id)               AS total_orders,
    ROUND(AVG(r.review_score), 2)   AS avg_review_score
FROM olist_orders_dataset o
JOIN olist_order_reviews_dataset r
    ON o.order_id = r.order_id
WHERE o.order_status = 'delivered'
  AND o.order_delivered_customer_date IS NOT NULL
GROUP BY delivery_bucket
ORDER BY avg_review_score DESC;


-- ----------------------------------------------------------
-- Q13. Which product categories have the highest average review score?
-- (minimum 100 reviews for statistical significance)
-- Business use: Quality benchmarking by category
-- ----------------------------------------------------------
SELECT
    cat.product_category_name_english   AS category,
    COUNT(r.review_id)                  AS total_reviews,
    ROUND(AVG(r.review_score), 2)       AS avg_review_score
FROM olist_order_reviews_dataset r
JOIN olist_orders_dataset o
    ON r.order_id = o.order_id
JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
JOIN olist_products_dataset pr
    ON oi.product_id = pr.product_id
JOIN olist_product_category_name_translation cat
    ON pr.product_category_name = cat.product_category_name
GROUP BY cat.product_category_name_english
HAVING COUNT(r.review_id) >= 100
ORDER BY avg_review_score DESC
LIMIT 15;


-- ----------------------------------------------------------
-- Q14. What percentage of orders were delivered late?
-- Business use: SLA breach rate — operational KPI
-- ----------------------------------------------------------
SELECT
    COUNT(order_id)                                                     AS total_delivered,
    SUM(CASE
        WHEN order_delivered_customer_date > order_estimated_delivery_date
        THEN 1 ELSE 0
    END)                                                                AS late_orders,
    ROUND(
        100.0 * SUM(CASE
            WHEN order_delivered_customer_date > order_estimated_delivery_date
            THEN 1 ELSE 0
        END) / COUNT(order_id), 2
    )                                                                   AS late_rate_pct
FROM olist_orders_dataset
WHERE order_status = 'delivered'
  AND order_delivered_customer_date IS NOT NULL;


-- ----------------------------------------------------------
-- Q15. Repeat vs. one-time customers — what is the split?
-- Business use: Customer loyalty and retention baseline
-- ----------------------------------------------------------
SELECT
    purchase_frequency,
    COUNT(customer_unique_id)   AS customer_count,
    ROUND(
        100.0 * COUNT(customer_unique_id) / SUM(COUNT(customer_unique_id)) OVER(),
        2
    )                           AS pct_of_total
FROM (
    SELECT
        c.customer_unique_id,
        CASE
            WHEN COUNT(DISTINCT o.order_id) = 1 THEN 'One-time'
            ELSE 'Repeat'
        END AS purchase_frequency
    FROM olist_customers_dataset c
    JOIN olist_orders_dataset o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
) AS customer_segments
GROUP BY purchase_frequency;


-- ============================================================
-- LEVEL 3: ADVANCED
-- Core: CTEs, Window Functions, Multi-step analysis
-- ============================================================

-- ----------------------------------------------------------
-- Q16. RFM Customer Segmentation
-- Business use: Marketing segmentation — rank customers by
--               Recency, Frequency, Monetary value
-- ----------------------------------------------------------
WITH rfm_raw AS (
    SELECT
        c.customer_unique_id,
        MAX(o.order_purchase_timestamp)             AS last_purchase_date,
        COUNT(DISTINCT o.order_id)                  AS frequency,
        ROUND(SUM(p.payment_value), 2)              AS monetary
    FROM olist_customers_dataset c
    JOIN olist_orders_dataset o
        ON c.customer_id = o.customer_id
    JOIN olist_order_payments_dataset p
        ON o.order_id = p.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY c.customer_unique_id
),
rfm_scored AS (
    SELECT
        customer_unique_id,
        DATEDIFF('2018-10-17', last_purchase_date)  AS recency_days,
        frequency,
        monetary,
        NTILE(5) OVER (ORDER BY DATEDIFF('2018-10-17', last_purchase_date) ASC)  AS r_score,
        NTILE(5) OVER (ORDER BY frequency DESC)                                  AS f_score,
        NTILE(5) OVER (ORDER BY monetary DESC)                                   AS m_score
    FROM rfm_raw
)
SELECT
    customer_unique_id,
    recency_days,
    frequency,
    monetary,
    r_score,
    f_score,
    m_score,
    (r_score + f_score + m_score)   AS rfm_total_score,
    CASE
        WHEN (r_score + f_score + m_score) >= 13 THEN 'Champions'
        WHEN (r_score + f_score + m_score) >= 10 THEN 'Loyal Customers'
        WHEN (r_score + f_score + m_score) >= 7  THEN 'Potential Loyalists'
        WHEN (r_score + f_score + m_score) >= 5  THEN 'At Risk'
        ELSE 'Lost'
    END                             AS rfm_segment
FROM rfm_scored
ORDER BY rfm_total_score DESC;


-- ----------------------------------------------------------
-- Q17. Month-over-Month (MoM) revenue growth rate
-- Business use: Executive dashboard — growth velocity tracking
-- ----------------------------------------------------------
WITH monthly_revenue AS (
    SELECT
        DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')    AS month,
        ROUND(SUM(p.payment_value), 2)                      AS revenue
    FROM olist_orders_dataset o
    JOIN olist_order_payments_dataset p
        ON o.order_id = p.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
)
SELECT
    month,
    revenue,
    LAG(revenue) OVER (ORDER BY month)                          AS prev_month_revenue,
    ROUND(
        100.0 * (revenue - LAG(revenue) OVER (ORDER BY month))
              / NULLIF(LAG(revenue) OVER (ORDER BY month), 0),
        2
    )                                                           AS mom_growth_pct
FROM monthly_revenue
ORDER BY month;


-- ----------------------------------------------------------
-- Q18. Running cumulative revenue by month
-- Business use: Progress-to-target tracking on dashboards
-- ----------------------------------------------------------
WITH monthly AS (
    SELECT
        DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')    AS month,
        ROUND(SUM(p.payment_value), 2)                      AS monthly_revenue
    FROM olist_orders_dataset o
    JOIN olist_order_payments_dataset p ON o.order_id = p.order_id
    WHERE o.order_status = 'delivered'
    GROUP BY DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')
)
SELECT
    month,
    monthly_revenue,
    ROUND(SUM(monthly_revenue) OVER (ORDER BY month ROWS UNBOUNDED PRECEDING), 2) AS cumulative_revenue
FROM monthly
ORDER BY month;


-- ----------------------------------------------------------
-- Q19. Top 3 sellers per state by revenue (ranking within group)
-- Business use: Regional leaderboard — seller performance report
-- ----------------------------------------------------------
WITH seller_revenue AS (
    SELECT
        s.seller_state,
        oi.seller_id,
        ROUND(SUM(oi.price), 2) AS revenue
    FROM olist_order_items_dataset oi
    JOIN olist_sellers_dataset s
        ON oi.seller_id = s.seller_id
    GROUP BY s.seller_state, oi.seller_id
),
ranked AS (
    SELECT
        seller_state,
        seller_id,
        revenue,
        RANK() OVER (PARTITION BY seller_state ORDER BY revenue DESC) AS state_rank
    FROM seller_revenue
)
SELECT *
FROM ranked
WHERE state_rank <= 3
ORDER BY seller_state, state_rank;


-- ----------------------------------------------------------
-- Q20. Cohort Retention Analysis (purchase cohort by month)
-- Business use: Measure how well Olist retains customers month-by-month
-- ----------------------------------------------------------
WITH first_purchase AS (
    SELECT
        c.customer_unique_id,
        MIN(DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m')) AS cohort_month
    FROM olist_customers_dataset c
    JOIN olist_orders_dataset o ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
),
customer_activity AS (
    SELECT
        c.customer_unique_id,
        DATE_FORMAT(o.order_purchase_timestamp, '%Y-%m') AS activity_month
    FROM olist_customers_dataset c
    JOIN olist_orders_dataset o ON c.customer_id = o.customer_id
),
cohort_data AS (
    SELECT
        f.cohort_month,
        a.activity_month,
        COUNT(DISTINCT a.customer_unique_id) AS active_customers
    FROM first_purchase f
    JOIN customer_activity a USING (customer_unique_id)
    GROUP BY f.cohort_month, a.activity_month
)
SELECT
    cohort_month,
    activity_month,
    active_customers,
    FIRST_VALUE(active_customers) OVER (
        PARTITION BY cohort_month ORDER BY activity_month
    )                                               AS cohort_size,
    ROUND(
        100.0 * active_customers /
        FIRST_VALUE(active_customers) OVER (
            PARTITION BY cohort_month ORDER BY activity_month
        ), 2
    )                                               AS retention_rate_pct
FROM cohort_data
ORDER BY cohort_month, activity_month;


-- ============================================================
-- BONUS: BUSINESS INSIGHT QUERY
-- ----------------------------------------------------------
-- Q21. Full order summary — one query to rule them all
-- Business use: Master fact table for dashboard data source
-- ============================================================
SELECT
    o.order_id,
    o.order_status,
    o.order_purchase_timestamp,
    o.order_delivered_customer_date,
    o.order_estimated_delivery_date,
    DATEDIFF(
        o.order_delivered_customer_date,
        o.order_purchase_timestamp
    )                                                           AS actual_delivery_days,
    DATEDIFF(
        o.order_estimated_delivery_date,
        o.order_purchase_timestamp
    )                                                           AS estimated_delivery_days,
    CASE
        WHEN o.order_delivered_customer_date > o.order_estimated_delivery_date THEN 'Late'
        WHEN o.order_delivered_customer_date IS NULL THEN 'Not Delivered'
        ELSE 'On Time'
    END                                                         AS delivery_status,
    c.customer_state,
    c.customer_city,
    p.payment_type,
    p.payment_installments,
    ROUND(p.payment_value, 2)                                   AS payment_value_brl,
    r.review_score,
    cat.product_category_name_english                           AS product_category
FROM olist_orders_dataset o
LEFT JOIN olist_customers_dataset c
    ON o.customer_id = c.customer_id
LEFT JOIN olist_order_payments_dataset p
    ON o.order_id = p.order_id
LEFT JOIN olist_order_reviews_dataset r
    ON o.order_id = r.order_id
LEFT JOIN olist_order_items_dataset oi
    ON o.order_id = oi.order_id
LEFT JOIN olist_products_dataset pr
    ON oi.product_id = pr.product_id
LEFT JOIN olist_product_category_name_translation cat
    ON pr.product_category_name = cat.product_category_name
ORDER BY o.order_purchase_timestamp DESC;

-- ============================================================
-- END OF QUERY BANK
-- Total: 21 queries | 3 difficulty levels | 21 business questions
-- ============================================================
